version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  test:
    executor:
      name: node/default
      tag: '12.9.1'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
    test:
      jobs:
        - test