# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Add some confidence

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  confidence:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 'lts/*' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm test
#     - run: npm run compile-typescript
